### PR TITLE
Remove unused imports and variables and fix other linter warnings

### LINKED ISSUE #510: Fix linter warnings
When docker is starting up the frontend, it spits out a few dozen linter errors, including unused variable warnings like this:
```
frontend_1  | src/components/Login/LoginButton.tsx
frontend_1  |   Line 3:8:  'btn_google_signin' is defined but never used  @typescript-eslint/no-unused-vars
```
And some of these:
```
Expected '===' and instead saw '=='   eqeqeq
```
These all look pretty easy to fix. We should go through all of them, replace the `==`'s with `===` after checking that `===` will work, and delete the unused variables. We can run the linter outside of docker with `npm run lint` to make sure we got all of them.

### PR DESCRIPTION
**Pull request by Gabe-Mitnick**
Closes #510 

- delete a lot of unused imports and unused variables
- delete one unused file (please double check that this is ok to delete)
- add an alt text
- change a `==` to a `===`
- add a couple things to .gitignore

This touches a lot code that I didn't write myself, so please review this PR carefully.

### CODE REVIEW

File: frontend/src/components/Common/Banner.tsx [hunk 1]
```diff
@@ -11,13 +10,6 @@ import close from '../../assets/svg/common/close.svg'
 interface Props extends PropsFromRedux {}
 
 const Banner: FC<Props> = (props) => {
-  const location = useLocation();
-  const history = useHistory();
-
-  function redirect(site: string) {
```
Comment (christinas24) [inline frontend/src/components/Common/Banner.tsx:17]: Let's keep this redirect function and use it for future external links. Using the redirect route allows us to view analytics of users clicking on the link.
You can add a comment noting to use this function in the future for external links instead of `href`.

**Review by christinas24 — CHANGES_REQUESTED** [review]

**Review by christinas24 — APPROVED** [review]
Thanks for fixing these @Gabe-Mitnick
